"""Add comment_ratings table

Revision ID: a9d9b63dfee8
Revises: 5aeabb342357
Create Date: 2026-08-07 09:17:24.754117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9d9b63dfee8'
down_revision: Union[str, Sequence[str], None] = '5aeabb342357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_ratings',
    sa.Column('comment_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id', 'user_id', name='uq_comment_rating_user')
    )
    op.create_index(op.f('ix_comment_ratings_comment_id'), 'comment_ratings', ['comment_id'], unique=False)
    op.create_index(op.f('ix_comment_ratings_user_id'), 'comment_ratings', ['user_id'], unique=False)
    op.drop_column('comments', 'rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_comment_ratings_user_id'), table_name='comment_ratings')
    op.drop_index(op.f('ix_comment_ratings_comment_id'), table_name='comment_ratings')
    op.drop_table('comment_ratings')
    # ### end Alembic commands ###
